name: Streamlit App CI/CD

on:
  push:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
        
      - name: Install flake8
        run: pip install flake8
        
      - name: Run flake8 Linting
        run: flake8 *.py --ignore=E501

  ########## Building the streamlit app ######## 
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Check for CSV file
        run: |
          if [ ! -f spotify-2023.csv ]; then
            echo "spotify-2023.csv not found"
            exit 1
          fi

      - name: Test Streamlit app
        run: streamlit run app.py

  ########## Deploying to Web server ######## 
  deploy:
    name: Deploy streamlit app
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Installing dependencies
        run: pip install -r requirements.txt
        
      - name: Deploy to Render.com
        uses: ttskch/render-deploy@v1.0.0
        with:
          service-id: ${{ secrets.SERVICEID }}
          api-key: ${{ secrets.RENDER }}